export const UsersConstants = {
  FORGOT_PASSWORD_EXPIRY_MS: 3600000,
  LOGIN_ACTIVITY_INTERVAL_MS: 10 * 60 * 1000,
  REGISTER_RATE_LIMIT: 1,
  RESEND_RATE_LIMIT: 1,
  MAX_LOGIN_ATTEMPTS: 4,
  VERIFICATION_TOKEN_BYTES: 256,
};
